---
- hosts: web
  become: yes
  tasks:

    - name: Copy WAR file to Tomcat
      copy:
        src: target/myapp.war
        dest: /opt/tomcat/webapps/myapp.war
      notify: restart tomcat

  handlers:
    - name: restart tomcat
      service:
        name: tomcat
        state: restarted
